#!/usr/bin/env zsh
#

if [ -e ./.git/hooks/pre-push ]; then
    echo "Running local pre push"
    ./.git/hooks/pre-push "$@"
fi

echo "\033[38;5;046m"
echo "Pushing following commits"
git cherry -v
echo "\033[0m"
